"""Initial schema: companies, users, vendors, invoices, line items, findings, audit events.

Revision ID: 2baaebc8aaae
Revises: 
Create Date: 2026-10-04 17:29:55.894061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2baaebc8aaae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_table('users',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'reviewer', name='role', native_enum=False, create_constraint=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'reviewer')", name=op.f('ck_users_role')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_table('vendors',
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('legal_name', sa.String(length=300), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_vendors_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('company_id', 'gstin', name='uq_vendors_company_gstin')
    )
    op.create_index('ix_vendors_company_display_name', 'vendors', ['company_id', 'display_name'], unique=False)
    op.create_table('invoices',
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'needs_review', 'approved', 'rejected', 'failed', name='status', native_enum=False, create_constraint=False, length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.Enum('text_layer', 'vision', name='extraction_method', native_enum=False, create_constraint=False, length=20), nullable=True),
    sa.Column('extraction_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('vendor_name', sa.String(length=300), nullable=True),
    sa.Column('vendor_gstin', sa.String(length=32), nullable=True),
    sa.Column('buyer_gstin', sa.String(length=32), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cgst', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sgst', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('igst', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('field_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("extraction_method IN ('text_layer', 'vision')", name=op.f('ck_invoices_extraction_method')),
    sa.CheckConstraint("status IN ('queued', 'processing', 'needs_review', 'approved', 'rejected', 'failed')", name=op.f('ck_invoices_status')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_invoices_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_invoices_reviewed_by_id_users')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_invoices_uploaded_by_id_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_invoices_vendor_id_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index('ix_invoices_company_created_at', 'invoices', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_invoices_company_due_date', 'invoices', ['company_id', 'due_date'], unique=False)
    op.create_index('ix_invoices_company_invoice_date', 'invoices', ['company_id', 'invoice_date'], unique=False)
    op.create_index('ix_invoices_company_sha256', 'invoices', ['company_id', 'file_sha256'], unique=False)
    op.create_index('ix_invoices_company_status', 'invoices', ['company_id', 'status'], unique=False)
    op.create_index('ix_invoices_company_total', 'invoices', ['company_id', 'total'], unique=False)
    op.create_index('ix_invoices_company_vendor', 'invoices', ['company_id', 'vendor_id'], unique=False)
    op.create_index('ix_invoices_duplicate_key', 'invoices', ['company_id', 'vendor_gstin', 'invoice_number'], unique=False)
    op.create_table('audit_events',
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('invoice_uploaded', 'extraction_started', 'extraction_completed', 'extraction_failed', 'extraction_retried', 'vendor_linked', 'vendor_created', 'vendor_updated', 'field_corrected', 'line_item_added', 'line_item_corrected', 'line_item_removed', 'invoice_approved', 'invoice_rejected', name='action', native_enum=False, create_constraint=False, length=40), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("action IN ('invoice_uploaded', 'extraction_started', 'extraction_completed', 'extraction_failed', 'extraction_retried', 'vendor_linked', 'vendor_created', 'vendor_updated', 'field_corrected', 'line_item_added', 'line_item_corrected', 'line_item_removed', 'invoice_approved', 'invoice_rejected')", name=op.f('ck_audit_events_action')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_audit_events_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_audit_events_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_company_created', 'audit_events', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_audit_company_entity', 'audit_events', ['company_id', 'entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index('ix_audit_company_invoice_created', 'audit_events', ['company_id', 'invoice_id', 'created_at'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hsn_sac', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_invoice_line_items_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_line_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line_items'))
    )
    op.create_index('ix_line_items_company_invoice', 'invoice_line_items', ['company_id', 'invoice_id', 'position'], unique=False)
    op.create_table('validation_findings',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('error', 'warning', 'info', name='severity', native_enum=False, create_constraint=False, length=10), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("severity IN ('error', 'warning', 'info')", name=op.f('ck_validation_findings_severity')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_validation_findings_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_validation_findings_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_findings'))
    )
    op.create_index('ix_findings_company_invoice', 'validation_findings', ['company_id', 'invoice_id'], unique=False)
    op.create_index('ix_findings_company_severity', 'validation_findings', ['company_id', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_findings_company_severity', table_name='validation_findings')
    op.drop_index('ix_findings_company_invoice', table_name='validation_findings')
    op.drop_table('validation_findings')
    op.drop_index('ix_line_items_company_invoice', table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index('ix_audit_company_invoice_created', table_name='audit_events')
    op.drop_index('ix_audit_company_entity', table_name='audit_events')
    op.drop_index('ix_audit_company_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_invoices_duplicate_key', table_name='invoices')
    op.drop_index('ix_invoices_company_vendor', table_name='invoices')
    op.drop_index('ix_invoices_company_total', table_name='invoices')
    op.drop_index('ix_invoices_company_status', table_name='invoices')
    op.drop_index('ix_invoices_company_sha256', table_name='invoices')
    op.drop_index('ix_invoices_company_invoice_date', table_name='invoices')
    op.drop_index('ix_invoices_company_due_date', table_name='invoices')
    op.drop_index('ix_invoices_company_created_at', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_vendors_company_display_name', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
